name 'mw_application_service'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mw_application_service'
long_description 'Installs/Configures mw_application_service'
version '0.1.0'

depends 'chef-sugar', '~> 3.0'
depends 'systemd', '~> 1.1.0'
